#!/usr/bin/env python3
"""List symbols that are at — or just set — a new 52-week low.

Reads public.stock_full_history (the same price series the chart draws) from
Supabase, computes each symbol's trailing-252-close minimum (the same window
live_scan uses for l52/h52 — falls back to min(prices) for symbols with fewer
than 252 closes), then flags symbols where:

  * at_52w_low  : latest close is within `--near-pct`% of the 52-week low
  * new_52w_low : the lowest close of the trailing `--days` bars equals the
                   52-week low — i.e. a fresh 52-week low was made within the
                   last `--days` trading days

Usage (from the server root):
  python scripts/fifty_two_week_low.py                 # lows in last 30 trading days
  python scripts/fifty_two_week_low.py --days 7        # only very recent lows
  python scripts/fifty_two_week_low.py --near-pct 0    # strict: exactly at the low
  python scripts/fifty_two_week_low.py --near-pct 15   # within 15% of the low (52WL tab)
  python scripts/fifty_two_week_low.py --top 50        # print only the top 50 rows
  python scripts/fifty_two_week_low.py --csv lows.csv  # also write results as CSV

Report only — writes nothing to the database.
"""
from __future__ import annotations

import argparse
import csv
import json
import os
import sys
import urllib.request
from pathlib import Path

SERVER_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(SERVER_ROOT))

ENV_CANDIDATES = (
    SERVER_ROOT / ".env",
    SERVER_ROOT / "Lakshmimata" / ".env",
    SERVER_ROOT.parent / "Lakshmimata" / ".env",
)
PAGE = 200


def load_env() -> tuple[str, str]:
    url = os.environ.get("SUPABASE_URL") or os.environ.get("VITE_SUPABASE_URL")
    key = os.environ.get("SUPABASE_SERVICE_KEY") or os.environ.get("VITE_SUPABASE_ANON_KEY")
    for env_file in ENV_CANDIDATES:
        if url and key:
            break
        if not env_file.is_file():
            continue
        for line in env_file.read_text(encoding="utf-8-sig").splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, _, v = line.partition("=")
            k, v = k.strip(), v.strip().strip('"').strip("'")
            if k in ("SUPABASE_URL", "VITE_SUPABASE_URL") and not url:
                url = v
            if k in ("SUPABASE_SERVICE_KEY", "VITE_SUPABASE_ANON_KEY") and not key:
                key = v
    if not url or not key:
        sys.exit("Missing Supabase URL/key (SUPABASE_URL + SUPABASE_SERVICE_KEY)")
    return url.rstrip("/"), key


def _request(base: str, key: str, path: str) -> list:
    headers = {
        "apikey": key,
        "Authorization": f"Bearer {key}",
        "Accept": "application/json",
    }
    req = urllib.request.Request(f"{base}{path}", headers=headers)
    with urllib.request.urlopen(req, timeout=120) as resp:
        raw = resp.read().decode()
    return json.loads(raw) if raw.strip() else []


def as_list(v) -> list:
    if v is None:
        return []
    if isinstance(v, str):
        try:
            v = json.loads(v)
        except json.JSONDecodeError:
            return []
    return v if isinstance(v, list) else []


def to_float(seq: list):
    """Coerce a price array to floats; return (floats, ok) where ok is False if
    any element is missing/NaN-like so the caller can skip a broken row."""
    out = []
    for x in seq:
        try:
            out.append(float(x))
        except (TypeError, ValueError):
            return [], False
    return out, True


def fifty_two_week_low(closes: list) -> float | None:
    """Trailing 252-close minimum, same window as live_scan's l52. Returns
    min(closes) for shorter histories."""
    if not closes:
        return None
    window = closes[-252:] if len(closes) >= 252 else closes
    return min(window)


def dashboard_records(hits: list) -> list:
    """Flatten scanner hits into the camelCase shape the HTML dashboard reads
    directly (same keys as 52week_low_dashboard.html's `computed` records)."""
    recs = []
    for h in hits:
        recs.append({
            "sym": h["sym"],
            "lowDate": h["low_date"],
            "lowClose": h["low_close"],
            "latest": h["latest_close"],
            "pctFrom52": h["pct_from_52wl"],
            "new52w": bool(h["new_52w_low"]),
            "atLow": bool(h.get("at_52w_low", False)),
            "barsSinceLow": h["bars_since_low"],
            "n": h["n_bars"],
            "short": bool(h["short_hist"]),
        })
    return recs


def dashboard_js_text(records: list) -> str:
    """Produce a .js file body that sets window.LOW_DASH_DATA for the dashboard."""
    items = ",\n".join("  " + json.dumps(r) for r in records) if records else ""
    return ("// Auto-generated by fifty_two_week_low.py — 52-week low data.\n"
            "window.LOW_DASH_DATA = [\n" + items + "\n];\n")


def emit_dashboard(records: list, emit_js: str | None, html_path: str | None) -> None:
    """Write the offline dashboard data. Either the sidecar JS (--emit-js) and/or
    a fully self-contained HTML (--html) with the data embedded inline."""
    if emit_js:
        Path(emit_js).write_text(dashboard_js_text(records), encoding="utf-8")
        print(f"Wrote dashboard data -> {emit_js} ({len(records)} rows)")
    if html_path:
        template = SERVER_ROOT.parent / "Lakshmimata" / "52week_low_dashboard.html"
        if not template.is_file():
            print(f"[html] template not found at {template}; skipping self-contained HTML")
            return
        js = dashboard_js_text(records).rstrip()
        html = template.read_text(encoding="utf-8")
        slot = '<script src="52week_low_data.js"></script>'
        if slot in html:
            html = html.replace(slot, "<script>\n" + js + "\n</script>")
        else:
            print("[html] sidecar slot marker not found in the dashboard template; "
                  "wrote data-only sidecar beside it instead")
        Path(html_path).write_text(html, encoding="utf-8")
        print(f"Wrote self-contained dashboard -> {html_path} ({len(records)} rows)")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--days", type=int, default=30,
                        help="count a low only if it was set within the last N "
                             "trading days (default 30)")
    parser.add_argument("--near-pct", type=float, default=0.0,
                        help="include symbols whose latest close is within this "
                             "%% above their 52-week low (0 = exactly at the low)")
    parser.add_argument("--top", type=int, default=None,
                        help="print only the top N rows")
    parser.add_argument("--csv", default=None,
                        help="optional CSV output path")
    parser.add_argument("--emit-js", default=None, metavar="PATH",
                        help="write a 52week_low_data.js sidecar for the offline "
                             "HTML dashboard (loads from file:// with no network)")
    parser.add_argument("--html", default=None, metavar="PATH",
                        help="write a fully self-contained dashboard HTML with the "
                             "data embedded (double-click to open, no server needed)")
    args = parser.parse_args()
    if args.days < 1:
        sys.exit("--days must be >= 1")

    base, key = load_env()
    print(f"Scanning stock_full_history for 52-week lows in the last "
          f"{args.days} trading day(s) (within {args.near_pct:g}% of low)…")

    hits = []
    offset = 0
    scanned = 0
    skipped = 0
    while True:
        rows = _request(
            base, key,
            "/rest/v1/stock_full_history"
            "?select=sym,dates,prices"
            f"&limit={PAGE}&offset={offset}",
        )
        if not rows:
            break
        for row in rows:
            sym = str(row.get("sym") or "").strip().upper()
            if not sym:
                continue
            closes_raw = as_list(row.get("prices"))
            dates = as_list(row.get("dates"))
            closes, ok = to_float(closes_raw)
            if not ok or not closes:
                skipped += 1
                continue
            if dates and len(dates) != len(closes):
                # Only a hard skip if dates exist but the arrays aren't aligned;
                # otherwise we still scan and leave the low-date blank.
                if len(dates) != len(closes) and len(dates) > 1:
                    skipped += 1
                    continue
            scanned += 1

            l52 = fifty_two_week_low(closes)
            if l52 is None or l52 <= 0:
                skipped += 1
                continue
            latest = closes[-1]

            # The trailing `days` bars — the "last 30 days" window.
            tail = closes[-args.days:]
            tail_min = min(tail)

            # A NEW 52-week low was set if the window minimum actually lives in
            # the recent tail (equals the trailing-252 minimum).
            new_52w_low = tail_min <= l52 * (1.0 + 1e-9)
            pct_from_52wl = (latest / l52 - 1.0) * 100.0
            at_52w_low = pct_from_52wl <= args.near_pct

            if not (new_52w_low or at_52w_low):
                continue

            # The low bar metadata is computed against the FULL closes array
            # (not the tail) so that "at the low" rows — where the low happened
            # before the recent window — are still surfaced correctly. The low
            # bar is the LAST occurrence of the window minimum.
            low_indices = [i for i, c in enumerate(closes) if c <= l52 * (1.0 + 1e-9)]
            if not low_indices:
                continue
            low_abs = max(low_indices)
            low_close = closes[low_abs]
            low_date = None
            if dates and len(dates) == len(closes):
                low_date = dates[low_abs]
            bars_since_low = len(closes) - 1 - low_abs

            hits.append({
                "sym": sym,
                "low_date": low_date,
                "low_close": round(low_close, 2),
                "latest_close": round(latest, 2),
                "pct_from_52wl": round(pct_from_52wl, 2),
                "new_52w_low": new_52w_low,
                "at_52w_low": at_52w_low,
                "bars_since_low": bars_since_low,
                "n_bars": len(closes),
                "short_hist": len(closes) < 252,
            })
        if len(rows) < PAGE:
            break
        offset += PAGE

    # Most recent lows first, then closest-to-low.
    hits.sort(
        key=lambda h: (h["new_52w_low"] is False, h["low_date"] or "", h["pct_from_52wl"])
    )
    if args.top:
        hits = hits[: args.top]

    n_new = sum(1 for h in hits if h["new_52w_low"])
    print(f"\nScanned {scanned} symbols ({skipped} skipped for missing/broken data).")
    print(f"52-week lows in the last {args.days} trading day(s): {len(hits)} "
          f"({n_new} set a NEW 52-week low in that window).")

    # Write offline dashboard files even when the result set is empty, so the
    # page can still be opened and will simply show "no symbols".
    if args.emit_js or args.html:
        emit_dashboard(dashboard_records(hits), args.emit_js, args.html)

    if not hits:
        print("\nNo symbols matched.")
        return

    header = ("SYM      low_date    low_close  latest   %from52W  new52w  "
              "barsAgo  history")
    print("\n" + header)
    print("-" * len(header))
    for h in hits:
        print(
            f"{h['sym']:<9} {str(h['low_date'] or '-'):<11} "
            f"{h['low_close']:<10} {h['latest_close']:<8} "
            f"{h['pct_from_52wl']:<8} "
            f"{'YES' if h['new_52w_low'] else '-':<7} "
            f"{h['bars_since_low']:<7} "
            f"{'short' if h['short_hist'] else 'full'}"
        )

    if args.csv:
        with open(args.csv, "w", newline="", encoding="utf-8") as fh:
            fieldnames = ["sym", "low_date", "low_close", "latest_close",
                          "pct_from_52wl", "new_52w_low", "bars_since_low",
                          "n_bars", "short_hist"]
            writer = csv.DictWriter(fh, fieldnames=fieldnames)
            writer.writeheader()
            for h in hits:
                writer.writerow(h)
        print(f"\nWrote {len(hits)} rows to {args.csv}")


if __name__ == "__main__":
    raise SystemExit(main())