"""
One-time load of downloaded index history CSVs into index_price_history.

Reads the CSVs produced by fetch_index_history_csv.py and either emits a SQL
file to paste into the Supabase SQL editor (default) or pushes straight to
Supabase when SUPABASE_URL / SUPABASE_SERVICE_KEY are set.

Usage:
    python scripts/fetch_index_history_csv.py --years 20
    python scripts/load_index_history.py                 # writes .sql
    python scripts/load_index_history.py --push          # needs env vars

index_price_history stores a bare `prices` JSON array with no dates, so only
the close column is loaded; the backend splices fresh Upstox days onto the
tail of this series on its next run.
"""

import argparse
import csv
import json
import os
import sys
import urllib.request

# Nifty 50 already has a working multi-year seed in the DB, so it is opt-in
# here — the point of this load is Midcap/Smallcap depth.
DEFAULT_INDEXES = ["Midcap 150", "Smallcap 250"]
CSV_NAMES = {
    "Nifty 50": "nifty_50.csv",
    "Midcap 150": "midcap_150.csv",
    "Smallcap 250": "smallcap_250.csv",
}

# Matches _index_series_has_corrupt_jumps in live_scan.py — a series with a
# bigger day-over-day move than this gets discarded by the backend on load.
MAX_DAILY_JUMP = 0.45


def read_closes(path):
    closes = []
    with open(path, newline="", encoding="utf-8") as fh:
        for row in csv.DictReader(fh):
            raw = row.get("close")
            if raw in (None, "", "null"):
                continue
            closes.append(round(float(raw), 2))
    return closes


def find_bad_jump(closes):
    for i in range(1, len(closes)):
        a, b = closes[i - 1], closes[i]
        if a > 0 and abs(b - a) / a > MAX_DAILY_JUMP:
            return i, a, b
    return None


def sql_escape(value):
    return value.replace("'", "''")


def build_sql(series):
    lines = [
        "-- One-time index history load (generated by scripts/load_index_history.py).",
        "-- Overwrites the `prices` array for each index; safe to re-run.",
        "",
    ]
    for name, closes in series:
        payload = sql_escape(json.dumps(closes, separators=(",", ":")))
        lines.append(f"-- {name}: {len(closes)} daily closes")
        lines.append("INSERT INTO public.index_price_history (name, prices, updated_at)")
        lines.append(f"VALUES ('{sql_escape(name)}', '{payload}'::jsonb, now())")
        lines.append("ON CONFLICT (name) DO UPDATE")
        lines.append("  SET prices = EXCLUDED.prices, updated_at = now();")
        lines.append("")
    return "\n".join(lines)


def push_to_supabase(series, url, key):
    endpoint = f"{url.rstrip('/')}/rest/v1/index_price_history?on_conflict=name"
    headers = {
        "apikey": key,
        "Authorization": f"Bearer {key}",
        "Content-Type": "application/json",
        "Prefer": "resolution=merge-duplicates,return=minimal",
    }
    for name, closes in series:
        body = json.dumps({"name": name, "prices": closes}).encode("utf-8")
        req = urllib.request.Request(endpoint, data=body, headers=headers, method="POST")
        with urllib.request.urlopen(req, timeout=60) as resp:
            print(f"  pushed {name}: {len(closes)} days (HTTP {resp.status})")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--csv-dir", default="data/indices", help="Where the CSVs live")
    ap.add_argument("--out", default="backfill_index_price_history.sql",
                    help="SQL file to write")
    ap.add_argument("--index", action="append", help="Index name; repeatable")
    ap.add_argument("--include-nifty", action="store_true",
                    help="Also load Nifty 50 (already seeded in most deployments)")
    ap.add_argument("--push", action="store_true",
                    help="Write directly to Supabase instead of emitting SQL")
    args = ap.parse_args()

    wanted = args.index or list(DEFAULT_INDEXES)
    if args.include_nifty and "Nifty 50" not in wanted:
        wanted.insert(0, "Nifty 50")

    series = []
    for name in wanted:
        filename = CSV_NAMES.get(name)
        if not filename:
            print(f"Unknown index '{name}'. Known: {', '.join(CSV_NAMES)}")
            return 1
        path = os.path.join(args.csv_dir, filename)
        if not os.path.exists(path):
            print(f"Missing {path} — run fetch_index_history_csv.py first")
            return 1

        closes = read_closes(path)
        if len(closes) < 252:
            print(f"{name}: only {len(closes)} days — too short to be useful")
            return 1

        bad = find_bad_jump(closes)
        if bad:
            i, a, b = bad
            print(f"{name}: suspicious {a} -> {b} jump at row {i}; "
                  "backend would discard this series")
            return 1

        print(f"  {name}: {len(closes)} closes, latest {closes[-1]}")
        series.append((name, closes))

    if args.push:
        url = os.environ.get("SUPABASE_URL")
        key = os.environ.get("SUPABASE_SERVICE_KEY") or os.environ.get("SUPABASE_KEY")
        if not url or not key:
            print("Set SUPABASE_URL and SUPABASE_SERVICE_KEY to use --push")
            return 1
        push_to_supabase(series, url, key)
        return 0

    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write(build_sql(series))
    size_kb = os.path.getsize(args.out) / 1024
    print(f"  wrote {args.out} ({size_kb:.0f} KB) — paste into the Supabase SQL editor")
    return 0


if __name__ == "__main__":
    sys.exit(main())
